/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sesion04.ui;

import com.mycompany.sesion04.ui.panels.PnlAlumnos;
import com.mycompany.sesion04.ui.panels.PnlMatricual;
import com.mycompany.sesion04.ui.panels.pnlCursos;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class EscuelaMain extends javax.swing.JFrame {

    /**
     * Creates new form EscuelaMain
     */
    PnlAlumnos pnlAlumnos = new PnlAlumnos();
    pnlCursos PnlCursos = new pnlCursos();
    PnlMatricual pnlMatricula = new PnlMatricual();
    public EscuelaMain() {
        initComponents();
        pnlMain.setLayout(new BorderLayout());
        pnlMain.add(PnlCursos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Configurar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        menuCursos = new javax.swing.JMenu();
        CursosGeneral = new javax.swing.JMenuItem();
        MenuAula = new javax.swing.JMenuItem();
        MenuAlumnos = new javax.swing.JMenu();
        AlumnosDatos = new javax.swing.JMenuItem();
        AlumnosCantidad = new javax.swing.JMenuItem();
        Matricula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Escuela");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        Archivo.setText("Archivo");

        Configurar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Configurar.setText("Configuración");
        Archivo.add(Configurar);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        jMenuBar1.add(Archivo);

        Consultas.setText("Consultas");

        menuCursos.setText("Cursos");
        menuCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuCursosItemStateChanged(evt);
            }
        });

        CursosGeneral.setText("General");
        CursosGeneral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CursosGeneralItemStateChanged(evt);
            }
        });
        CursosGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosGeneralActionPerformed(evt);
            }
        });
        menuCursos.add(CursosGeneral);

        MenuAula.setText("Por aula");
        MenuAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAulaActionPerformed(evt);
            }
        });
        menuCursos.add(MenuAula);

        Consultas.add(menuCursos);

        MenuAlumnos.setText("Alumnos");

        AlumnosDatos.setText("Datos");
        AlumnosDatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AlumnosDatosItemStateChanged(evt);
            }
        });
        AlumnosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnosDatosActionPerformed(evt);
            }
        });
        MenuAlumnos.add(AlumnosDatos);

        AlumnosCantidad.setText("jMenuItem6");
        MenuAlumnos.add(AlumnosCantidad);

        Consultas.add(MenuAlumnos);

        Matricula.setText("Matricula");
        Matricula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MatriculaItemStateChanged(evt);
            }
        });
        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });
        Consultas.add(Matricula);

        jMenuBar1.add(Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int op = JOptionPane.showConfirmDialog(this, 
                                "Deseas Salir?", 
                                "Estas seguro de lo que haces?", 
                                JOptionPane.OK_CANCEL_OPTION);
    if(op==0)  System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void CursosGeneralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CursosGeneralItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CursosGeneralItemStateChanged

    private void menuCursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuCursosItemStateChanged
        // TODO add your handling code here:
        

    }//GEN-LAST:event_menuCursosItemStateChanged

    private void AlumnosDatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AlumnosDatosItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_AlumnosDatosItemStateChanged

    private void MatriculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MatriculaItemStateChanged
        // TODO add your handling code here:
   

    }//GEN-LAST:event_MatriculaItemStateChanged

    private void MenuAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAulaActionPerformed

    private void CursosGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosGeneralActionPerformed
        // TODO add your handling code here:
        pnlMain.removeAll();
        pnlMain.add(PnlCursos);
        SwingUtilities.updateComponentTreeUI(pnlMain);
    }//GEN-LAST:event_CursosGeneralActionPerformed

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed
        // TODO add your handling code here:
        pnlMain.removeAll();
        pnlMain.add(pnlMatricula);
        SwingUtilities.updateComponentTreeUI(pnlMain);
    }//GEN-LAST:event_MatriculaActionPerformed

    private void AlumnosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnosDatosActionPerformed
        // TODO add your handling code here:
        pnlMain.removeAll();
        pnlMain.add(pnlAlumnos);
        SwingUtilities.updateComponentTreeUI(pnlMain);
    }//GEN-LAST:event_AlumnosDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscuelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscuelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscuelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscuelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscuelaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumnosCantidad;
    private javax.swing.JMenuItem AlumnosDatos;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Configurar;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem CursosGeneral;
    private javax.swing.JMenuItem Matricula;
    private javax.swing.JMenu MenuAlumnos;
    private javax.swing.JMenuItem MenuAula;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCursos;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
